name       : journal
version    : 1.0.1
release    : 3
source     :
    - https://github.com/solus-project/journal/archive/v1.0.1.tar.gz : 94afb8518fdb6dffdba7cb8bd14ca9ca6a1d631b47586537d8a1b693793961f9
license    : GPL-2.0
summary    : Journal text editor
description: |
     A lightweight text-editor with sharing and customizing options.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(gtksourceview-3.0)
    - vala
setup      : |
    mkdir build
    cd build
build      : |
    %cmake
    %make
install    : |
    %make_install
